### ISSUE TITLE
AddActionToRunAfterDetectChanges

### ISSUE THREAD

**Issue by arturaslt** [JonPSmith/EfCore.GenericEventRunner#4]
Hello,

We are using ChangeTracker to update entities, "LastUpdated" and "UserId", in extending DbContext with dependency injection, since we are using libraries, is there a way to send data to ChangeTracker Configuration ?

**Comment by JonPSmith** [comment]
I assume from your comment that you are using the configuration's `AddActionToRunAfterDetectChanges` method now, but you want to provide extra data to the function after `context.ChangeTracker.DetectChanges();`. I also assume that the data you want to provide changes during the the context's use (fixed values are, of course, simple).

If that is what you want to do I can't see a simple way to do that within the `GenericEventRunner` library, as the function is stored in the GenericEventRunner's configuration, which is registered as a singleton.

Have you thought about using [`context.ChangeTracker.StateChanged`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.changetracking.changetracker.statechanged?view=efcore-5.0)? It will trigger when (most) of the state changes happen. There isn't much EF Core docs on this, but have a look at [this issue I raised when writing the EF Core in action book](https://github.com/dotnet/efcore/issues/21852) will give you an idea. If you already have the [second edition of my book](https://bit.ly/EfCoreBookEd2), then I have a a whole section on this in section 11.4.4

**Comment by arturaslt** [comment]
Thank you for your response, I will take a look
