### ISSUE TITLE
Multiple event (with DbContext inside)-> loop infinite

### ISSUE THREAD

**Issue by trungphungduc** [JonPSmith/EfCore.GenericEventRunner#5]
I found a problem with this nuget, i just test on DuringEvent:

```
Function A
{
    ExecuteEvent1
    ExecuteEvent2 (have a SaveAsync inside this event2)
    SaveAsync()
}
```

----
Result:
Event1 and Event2 loop infinite.

Is it a bugs or something else ?

**Comment by JonPSmith** [comment]
Hi @trungphungduc,

Yes, calling SaveChanges within a before (or during) event handler will cause an infinite loop, but you don't need to call SaveChanges in an before/during event handler anyway. That's because you GenericEventRunner will call SaveChanges anyway.
