### ISSUE TITLE
IAfterSaveEventHandler Blocks Transaction

### ISSUE THREAD

**Issue by JEVietti** [JonPSmith/EfCore.GenericEventRunner#8]
I am trying to use the IAfterSaveEventHandlerAsync to send emails post transaction, however I am running into an issue in which the handler is blocking the transaction from completing and the endpoint from returning a response until after the handler complete. Furthermore any exception in the handler bails out of the transaction and calls a rollback.

From the diagram provided on the github: https://www.thereformedprogrammer.net/wp-content/uploads/2021/01/GenericEventRunnerTypesOfEvents.png

As well as the wiki resources itself, makes it seem as though the IAfterSaveEventHandler are called after CommitAsync is called, and
it is stated that all db updates are already sync'd and cannot be reverted.

I created a test posted below to make sure it wasn't something specific to my codebase, let me know if you need further details or if I am misunderstanding how to use the API.

```
[Fact]
        public async Task TestCreateDbWithDiForHandlersAfterHandlerDoNothingAsyncOk()
        {
            //SETUP
            var options = SqliteInMemory.CreateOptions<ExampleDbContext>();
            var logs = new List<LogOutput>();
            var context = options.CreateAndSeedDbWithDiForHandlers<OrderCreatedHandler>(logs);
            {
                using (var transaction = await context.Database.BeginTransactionAsync())
                {
                    //ATTEMPT
                    context.Database.EnsureCreated();
                    var entity = context.SeedTwoTaxRates().First();

                    //ATTEMPT
                    entity.AddEvent(new EventTestAfterExceptionHandler(), EventToSend.AfterSave);
                    await context.SaveChangesAsync();
                    // EXECUTING HERE & EXCEPTION
                    await transaction.CommitAsync();
                    // EXPECTED EXECUTION HERE
                }
                // THROWS AN EXCEPTION BEFORE TRANSACTION  CAN OCCUR
                //VERIFY
            }
        }
```
        
Thanks in advance.

**Comment by JonPSmith** [comment]
Hi @JEVietti,

Can you add the exception you get - that will help me to know what to look out for.

**Comment by JonPSmith** [comment]
Also, can you add the `new EventTestAfterExceptionHandler()` code too - thanks.

**Comment by JEVietti** [comment]
@JonPSmith 
It may be important to note that the code I posted above is just an added Test in the main repo, that I cloned, no other modifications have been made. 

Also to be a bit more clear the main concern isn't the exception necessarily but that the handler execution is blocking the commitAsync call, further execution. So if you have an async operation such as sending emails, it will wait until that code has completed, could me minutes/seconds, and then proceed to commit. And as mentioned previously the exception, if not caught will also be thrown before commit.

Here is the Exception

```
Test.UnitTests.InfrastructureTests.TestEventSaveChangesTransactionsAsync.TestCreateDbWithDiForHandlersAfterHandlerDoNothingAsyncOk

  Message: 
     System.ApplicationException : AfterHandlerThrowsException

  Stack Trace: 
     AfterHandlerThrowsException.Handle(Object callingEntity, EventTestAfterExceptionHandler domainEvent) line 14
     AfterSaveHandler`1.Handle(Object callingEntity, IEntityEvent entityEvent) line 26
     FindRunHandlers.RunHandlersForEventAsync(EntityAndEvent entityAndEvent, Int32 loopCount, BeforeDuringOrAfter beforeDuringOrAfter, Boolean allowAsync) line 70
     RunEachTypeOfEvents.RunAfterSaveChangesEventsAsync(DbContext context, Boolean allowAsync) line 160
     EventsRunner.RunEventsBeforeDuringAfterSaveChangesAsync(DbContext context, Func`1 callBaseSaveChangesAsync, CancellationToken cancellationToken) line 204
     DbContextWithEvents`1.SaveChangesWithStatusAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken) line 71
     DbContextWithEvents`1.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken) line 111
     TestEventSaveChangesTransactionsAsync.TestCreateDbWithDiForHandlersAfterHandlerDoNothingAsyncOk() line 268
--- End of stack trace from previous location where exception was thrown ---
```

So the `new EventTestAfterExceptionHandler()` is just the same code as it the repo, I only added a test nothing else.
Here it is though:
```
using GenericEventRunner.DomainParts;

namespace Test.EventsAndHandlers
{
    public class EventTestAfterExceptionHandler : IEntityEvent
    {
        
    }
}
```
This triggers the AfterHandlerThrowsException:
```
 public class AfterHandlerThrowsException : IAfterSaveEventHandler<EventTestAfterExceptionHandler>
    {
        public void Handle(object callingEntity, EventTestAfterExceptionHandler domainEvent)
        {
            throw new ApplicationException(nameof(AfterHandlerThrowsException));
        }
    }
  ```
It maybe important to note that in my own application this occurs in the relevant AsyncHandler as well.

**Comment by JonPSmith** [comment]
Hi @JEVietti ,

I'm sorry, I was busy with something else and I didn't properly read your question. I think I understand now so here are my answers.

>  I am running into an issue in which the handler is blocking the transaction from completing and the endpoint from returning a response until after the handler complete.

Yes, **any** long running event will slow down the saving of the data. In your case its at the end and you are using a transaction so its more obvious, but this is a general issue. If you need a quick database update then you make your events fast. In your case you should manually call the email sending instead of using events to get a quick database update.

> Furthermore any exception in the handler bails out of the transaction and calls a rollback.

If you aren't using a transaction, then a `IAfterSaveEventHandler` throwing an exception won't stop the data being written to the database. But if you use your own transaction, then you do need to either ensure a `IAfterSaveEventHandler` isn't going to throw an exception, or add extra code (say a try ... catch) to ensure that the commit is called.

**Comment by JEVietti** [comment]
Hey @JonPSmith,

Thanks for the clarification, I will say that I do think the [image ](https://www.thereformedprogrammer.net/wp-content/uploads/2021/01/GenericEventRunnerTypesOfEvents.png)posted on the repo/articles is misleading then, as it shows After Events running after transaction.CommitAsync() is called, and even explicitly states sending emails as a use case of the AfterSaveEvents. 

Unless I'm missing something you are suggesting that there is no way to have a non-blocking AfterSaveEvent Handler once SaveChangesAsync is called, and that I should simply call my own service instead. Essentially I am looking for a way to make the AfterSaveEvent and its Handler to act as a side-effect that is not blocking further execution after SaveChangesAsync is called, in order to not prevent commits or return reponses.

Also I'm not sure what you mean by using your own transaction, as I would think I would have to if I want the ability to rollback on exceptions from my own services, or other IBeforeSave and IDuringSave Handlers.

All that said, if this is in fact intended behavior, feel free to close.

EDIT: After thinking about this some more, while I think the first paragraph I responded with still has some merit in terms in what is suggested vs reality. I do think the solution is for me to speed up the Handler, by using a separate thread, Fire and Forget, or something similar, so that the handler itself is not awaiting the emails being sent, catches any exceptions that would prevent my transaction from completing, and returns quickly. 

If you have a suggestion about what to use inside the handler in order to achieve this, by not awaiting the async call sending of the emails or otherwise, I'd appreciate that. In any case, I think that wraps up this issue, unless you think otherwise.

**Comment by JonPSmith** [comment]
Hi @JEVietti,

Your questions / comments show that the documentation isn't good enough, so I have updated the [Handing errors and exceptions](https://github.com/JonPSmith/EfCore.GenericEventRunner/wiki/Handing-errors-and-exceptions) documentation to add extra information on what happens with Exceptions. The [last section of this document](https://github.com/JonPSmith/EfCore.GenericEventRunner/wiki/Handing-errors-and-exceptions#after-events) gives guidance on After events.

> Also I'm not sure what you mean by using your own transaction, as I would think I would have to if I want the ability to rollback on exceptions from my own services, or other IBeforeSave and IDuringSave Handlers.

In the case of a Before or During event returning an error / Exception the GenericEventRunner will ensure that the database isn't updated, so you don't need to create a transaction unless you need one for your own use. If you don't create a transaction, then the GenericEventRunner will create a transaction if needed, for instance if there are any During events.

> If you have a suggestion about what to use inside the handler in order to achieve this, by not awaiting the async call sending of the emails or otherwise.

I have used a [ASP.NET Core backgroundservice](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services#backgroundservice-base-class) for long-running services. [This section](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services#queued-background-tasks) shows how to send messages to a `backgroundservice`. NOTE: I haven't that exact queued task approach and there are some issues around backgroundservice if you have multiple instances of your web app running, so be aware.
